error: add type hints
In particular, let error() take anything as a message, because we just
need to print it

We use this with Exceptions from ident.py